CREATE TABLE USERS( 
USER_ID NUMBER(10,0) PRIMARY KEY,
USER_NAME VARCHAR2(50) NOT NULL,
USER_EMAIL VARCHAR2(100) NOT NULL,
USER_PASSWORD VARCHAR2(100) NOT NULL,
USER_CREATEDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE USERS1;

INSERT INTO USERS VALUES(USERS1.nextval,'홍길동','hong@exmaple.co.kr','password123',DEFAULT);
INSERT INTO USERS VALUES(USERS1.nextval,'김철수','kim@example.com','mypassword',DEFAULT);
INSERT INTO USERS VALUES(USERS1.nextval,'이영희','lee@example.com','securepass',DEFAULT);

SELECT * FROM USERS;